// ============================================================================
// NEXORA STOCK MARKET GAME DATA LAYER
// ============================================================================

export const RARITY_COLORS = {
  COMMON: { label: 'Rookie / Starter', color: '#94A3B8', border: 'rgba(148, 163, 184, 0.4)', bg: 'rgba(148, 163, 184, 0.1)' },
  RARE: { label: 'Rare AI', color: '#06B6D4', border: 'rgba(6, 182, 212, 0.4)', bg: 'rgba(6, 182, 212, 0.1)' },
  EPIC: { label: 'Epic AI', color: '#A855F7', border: 'rgba(168, 85, 247, 0.4)', bg: 'rgba(168, 85, 247, 0.1)' },
  LEGENDARY: { label: 'Legendary AI', color: '#F59E0B', border: 'rgba(245, 158, 11, 0.4)', bg: 'rgba(245, 158, 11, 0.1)' },
  MYTHIC: { label: 'Mythic Whale', color: '#EC4899', border: 'rgba(236, 72, 153, 0.4)', bg: 'rgba(236, 72, 153, 0.1)' },
};

export const AGENTS_CATALOG = [
  {
    id: 'agent-scout',
    name: 'SCOUT',
    title: 'Rookie Market Scout',
    rarity: 'COMMON',
    unlockCostGems: 0, // FREE starter agent
    isStarter: true,
    orbColor: 'violet',
    avatarGlow: '#8B5CF6',
    level: 1,
    skillName: 'Basic Trend Radar',
    skillDescription: 'Identifies oversold dips & basic momentum breakouts to guide rookie trading missions.',
    perks: [
      'Beginner signal alerts (+10% guidance accuracy)',
      'Guides rookie mission task completion',
      'Basic stop-loss indicators'
    ],
    stats: { accuracy: 70, speed: 65, profitBonus: 0, shield: 20 },
    bio: 'Your loyal starter AI delegate. SCOUT scans the ticker 24/7 to provide straightforward entry ideas and helps you earn your first Premium Nexus Gems.',
  },
  {
    id: 'agent-oracle',
    name: 'ORACLE',
    title: 'The Breakout Seer',
    rarity: 'RARE',
    unlockCostGems: 50,
    isStarter: false,
    orbColor: 'emerald',
    avatarGlow: '#10B981',
    level: 1,
    skillName: 'Predictive Dip & Surge Forecast',
    skillDescription: 'Forecasts price movements 10 seconds in advance with 85% algorithmic confidence.',
    perks: [
      '85% Win-rate buy/sell signal overlays',
      'Highlights optimal dip-buying entry points',
      '+10% extra profit bonus on swing trades'
    ],
    stats: { accuracy: 88, speed: 75, profitBonus: 10, shield: 45 },
    bio: 'Powered by predictive neural regression. ORACLE anticipates trend reversals before other market participants catch on.',
  },
  {
    id: 'agent-quantum',
    name: 'QUANTUM',
    title: 'High-Frequency Scalper',
    rarity: 'EPIC',
    unlockCostGems: 100,
    isStarter: false,
    orbColor: 'cyan',
    avatarGlow: '#06B6D4',
    level: 1,
    skillName: 'Passive Yield & Micro-Scalp',
    skillDescription: 'Generates passive token dividends (+5% every 30s) and captures lightning-fast spreads.',
    perks: [
      'Passive cash dividend yield ($25 every 30s)',
      'Sub-second trade execution speed',
      'Unlocks instant 1-click scalp orders'
    ],
    stats: { accuracy: 82, speed: 98, profitBonus: 15, shield: 50 },
    bio: 'An ultra-low latency algorithmic engine that harvests fractional spreads across the market ticker.',
  },
  {
    id: 'agent-valkyrie',
    name: 'VALKYRIE',
    title: 'Growth & Tech Hunter',
    rarity: 'EPIC',
    unlockCostGems: 175,
    isStarter: false,
    orbColor: 'pink',
    avatarGlow: '#EC4899',
    level: 1,
    skillName: '10x Profit Multiplier',
    skillDescription: 'Detects high-volatility semiconductor and AI stock rallies with +25% profit booster.',
    perks: [
      '+25% Profit multiplier on Technology & AI stocks',
      'Highlights 10x breakout momentum stocks',
      'Unlocks high-roller position sizes'
    ],
    stats: { accuracy: 90, speed: 85, profitBonus: 25, shield: 35 },
    bio: 'Relentless growth hunter specialized in high-beta tech equities and exponential semiconductor rallies.',
  },
  {
    id: 'agent-aegis',
    name: 'AEGIS',
    title: 'Crash Shield & Hedge Master',
    rarity: 'LEGENDARY',
    unlockCostGems: 250,
    isStarter: false,
    orbColor: 'gold',
    avatarGlow: '#F59E0B',
    level: 1,
    skillName: 'Max -2% Drawdown Shield',
    skillDescription: 'Auto-hedges your portfolio against sudden market dumps, capping any single trade loss at -2%.',
    perks: [
      'Maximum loss cap at -2% per position',
      'Early warning flash before market-wide crashes',
      'Emergency 1-click portfolio hedge'
    ],
    stats: { accuracy: 92, speed: 90, profitBonus: 15, shield: 99 },
    bio: 'The impenetrable risk optimizer. AEGIS guarantees you never blow up your account during unexpected flash crashes.',
  },
  {
    id: 'agent-titan',
    name: 'TITAN',
    title: 'The Market Whale',
    rarity: 'MYTHIC',
    unlockCostGems: 400,
    isStarter: false,
    orbColor: 'purple',
    avatarGlow: '#A855F7',
    level: 1,
    skillName: '3x Margin Leverage & Gem Dividends',
    skillDescription: 'Unlocks 3x Margin buying power and passively drops +5 💎 Nexus Gems per day.',
    perks: [
      '3x Margin buying power leverage',
      '+5 💎 Premium Nexus Gems daily bonus payout',
      '+35% Profit multiplier on all trades'
    ],
    stats: { accuracy: 99, speed: 95, profitBonus: 35, shield: 90 },
    bio: 'The apex market conqueror. TITAN possesses deep liquidity dominance, multiplying both trading cash and premium gem yields.',
  },
];

export const INITIAL_STOCKS = [
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    sector: 'AI & Semiconductors',
    price: 128.50,
    basePrice: 128.50,
    changePercent: 3.85,
    sparkline: [118, 120, 119, 122, 125, 124, 128.5],
    volatility: 'HIGH',
    logoColor: '#76B900',
    news: 'Next-Gen Cyber AI GPU cluster synthesis surges demand.',
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    sector: 'Consumer Tech',
    price: 224.20,
    basePrice: 224.20,
    changePercent: 1.45,
    sparkline: [218, 220, 221, 219, 223, 222, 224.2],
    volatility: 'LOW',
    logoColor: '#A2AAAD',
    news: 'New holographic spatial computing device breaks pre-order records.',
  },
  {
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    sector: 'Clean Energy & Robotics',
    price: 254.10,
    basePrice: 254.10,
    changePercent: 4.60,
    sparkline: [238, 242, 240, 248, 250, 249, 254.1],
    volatility: 'VERY HIGH',
    logoColor: '#E82127',
    news: 'Autonomous robotaxi fleet receives state certification.',
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corp.',
    sector: 'Cloud & AI Kernel',
    price: 448.90,
    basePrice: 448.90,
    changePercent: 2.10,
    sparkline: [435, 439, 442, 440, 445, 444, 448.9],
    volatility: 'MEDIUM',
    logoColor: '#00A4EF',
    news: 'Enterprise autonomous agent suite reaches 100M active instances.',
  },
  {
    symbol: 'PLTR',
    name: 'Palantir Technologies',
    sector: 'Defense AI & Data',
    price: 36.40,
    basePrice: 36.40,
    changePercent: 5.80,
    sparkline: [32, 33, 34, 33.5, 35, 34.8, 36.4],
    volatility: 'HIGH',
    logoColor: '#FFFFFF',
    news: 'Secures sovereign cloud intelligence contract for automated defense.',
  },
  {
    symbol: 'COIN',
    name: 'Coinbase Global',
    sector: 'Digital Assets Platform',
    price: 215.80,
    basePrice: 215.80,
    changePercent: -1.25,
    sparkline: [225, 222, 220, 218, 219, 217, 215.8],
    volatility: 'VERY HIGH',
    logoColor: '#0052FF',
    news: 'Consolidation phase detected as institutional trading volume spikes.',
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    sector: 'E-Commerce & AWS',
    price: 186.40,
    basePrice: 186.40,
    changePercent: -0.85,
    sparkline: [190, 189, 187, 188, 186, 187, 186.4],
    volatility: 'MEDIUM',
    logoColor: '#FF9900',
    news: 'AWS releases sub-millisecond AI inference micro-nodes.',
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    sector: 'AI Hardware & Chips',
    price: 154.20,
    basePrice: 154.20,
    changePercent: 2.75,
    sparkline: [146, 148, 150, 149, 152, 151, 154.2],
    volatility: 'HIGH',
    logoColor: '#ED1C24',
    news: 'Unveils next-gen APU processors outperforming benchmarks.',
  },
];

export const INITIAL_MISSIONS = [
  {
    id: 'm-rookie-1',
    tier: 'Rookie Onboarding',
    title: 'First Market Entry',
    description: 'Execute your first stock trade following SCOUT’s decision signal.',
    progress: 0,
    target: 1,
    unit: 'trades',
    rewardGems: 15,
    rewardCash: 500,
    claimed: false,
    badge: '🎯 First Blood',
  },
  {
    id: 'm-rookie-2',
    tier: 'Rookie Onboarding',
    title: 'Lock In First Profit',
    description: 'Sell a stock position with at least +$150 positive return.',
    progress: 0,
    target: 150,
    unit: '$ profit',
    rewardGems: 25,
    rewardCash: 750,
    claimed: false,
    badge: '💰 Green Trader',
  },
  {
    id: 'm-tier-1',
    tier: 'Daily Active Mission',
    title: 'Tech Sector Surge',
    description: 'Buy shares in 2 distinct AI or Semiconductor companies (NVDA, MSFT, AMD, PLTR).',
    progress: 0,
    target: 2,
    unit: 'tech stocks',
    rewardGems: 20,
    rewardCash: 600,
    claimed: false,
    badge: '⚡ Tech Pioneer',
  },
  {
    id: 'm-tier-2',
    tier: 'Market Master Quest',
    title: 'Accumulate $2,000 Total Profit',
    description: 'Earn a cumulative net trading profit of +$2,000 across all positions.',
    progress: 0,
    target: 2000,
    unit: '$ total gain',
    rewardGems: 45,
    rewardCash: 1500,
    claimed: false,
    badge: '📈 Profit Engine',
  },
  {
    id: 'm-tier-3',
    tier: 'Agent Forge Milestone',
    title: 'Recruit Your Second AI Agent',
    description: 'Spend your earned 💎 Nexus Gems in the Agent Forge to unlock ORACLE or QUANTUM.',
    progress: 1,
    target: 2,
    unit: 'agents owned',
    rewardGems: 50,
    rewardCash: 2500,
    claimed: false,
    badge: '🤖 Commander',
  },
];
