// ============================================================================
// STOCKBUILDERS FUTURISTIC STOCK MARKET GAMING DATA LAYER
// ============================================================================

export const RARITY_COLORS = {
  COMMON: { label: 'Rookie AI', color: '#94A3B8', border: 'rgba(148, 163, 184, 0.4)', bg: 'rgba(148, 163, 184, 0.12)', glow: 'rgba(148, 163, 184, 0.25)' },
  RARE: { label: 'Rare Sentinel', color: '#06B6D4', border: 'rgba(6, 182, 212, 0.45)', bg: 'rgba(6, 182, 212, 0.12)', glow: 'rgba(6, 182, 212, 0.35)' },
  EPIC: { label: 'Epic Cyber-Core', color: '#A855F7', border: 'rgba(168, 85, 247, 0.45)', bg: 'rgba(168, 85, 247, 0.12)', glow: 'rgba(168, 85, 247, 0.35)' },
  LEGENDARY: { label: 'Legendary Aegis', color: '#F59E0B', border: 'rgba(245, 158, 11, 0.5)', bg: 'rgba(245, 158, 11, 0.14)', glow: 'rgba(245, 158, 11, 0.4)' },
  MYTHIC: { label: 'Mythic Whale', color: '#EC4899', border: 'rgba(236, 72, 153, 0.55)', bg: 'rgba(236, 72, 153, 0.15)', glow: 'rgba(236, 72, 153, 0.45)' },
};

export const PLAYER_RANKS = [
  { level: 1, title: 'Rookie Scalper', icon: '🌱', minXP: 0 },
  { level: 5, title: 'Sector Scout', icon: '⚡', minXP: 500 },
  { level: 10, title: 'Breakout Hunter', icon: '🎯', minXP: 1500 },
  { level: 15, title: 'Neural Tactician', icon: '🧠', minXP: 3200 },
  { level: 20, title: 'High-Roller Arbitrageur', icon: '💎', minXP: 6000 },
  { level: 25, title: 'Market Commander', icon: '🚀', minXP: 10000 },
  { level: 30, title: 'Apex Syndicate Leader', icon: '👑', minXP: 16000 },
  { level: 40, title: 'Cyber Whale Overlord', icon: '🌌', minXP: 26000 },
  { level: 50, title: 'Galactic Market Legend', icon: '✨', minXP: 45000 },
];

export const LEAGUE_TIERS = [
  { id: 'bronze', name: 'Bronze League', minNetWorth: 0, color: '#CD7F32', badge: '🥉', promoReward: 15 },
  { id: 'silver', name: 'Silver League', minNetWorth: 15000, color: '#C0C0C0', badge: '🥈', promoReward: 30 },
  { id: 'gold', name: 'Gold League', minNetWorth: 35000, color: '#FFD700', badge: '🥇', promoReward: 50 },
  { id: 'platinum', name: 'Platinum League', minNetWorth: 75000, color: '#00FFFF', badge: '💎', promoReward: 80 },
  { id: 'diamond', name: 'Diamond League', minNetWorth: 150000, color: '#B9F2FF', badge: '💠', promoReward: 120 },
  { id: 'cyber_legend', name: 'Cyber Legend', minNetWorth: 300000, color: '#EC4899', badge: '👑', promoReward: 200 },
];

export const DAILY_STREAK_REWARDS = [
  { day: 1, title: 'Day 1 Starter Cache', cash: 500, gems: 5, xp: 50, icon: '💰' },
  { day: 2, title: 'Day 2 Data Core', cash: 750, gems: 10, xp: 80, icon: '💎' },
  { day: 3, title: 'Day 3 Speed Multiplier', cash: 1000, gems: 15, xp: 120, icon: '⚡' },
  { day: 4, title: 'Day 4 Quantum Capsule', cash: 1500, gems: 20, xp: 160, icon: '📦' },
  { day: 5, title: 'Day 5 Neural Booster', cash: 2000, gems: 30, xp: 220, icon: '🧠' },
  { day: 6, title: 'Day 6 Syndicate Loot', cash: 3000, gems: 40, xp: 300, icon: '🎁' },
  { day: 7, title: 'Day 7 Apex Cyber Vault', cash: 5000, gems: 75, xp: 500, icon: '👑' },
];

export const MARKET_EVENTS = [
  {
    id: 'event-ai-surge',
    title: '⚡ AI Quantum Rally',
    category: 'TECH_BOOST',
    description: 'Autonomous neural chips surge! Tech stocks gain +25% XP multiplier and +10% profit yield.',
    sectors: ['AI & Semiconductors', 'Cloud & AI Kernel', 'Defense AI & Data', 'AI Hardware & Chips'],
    xpMultiplier: 1.25,
    profitMultiplier: 1.10,
    gemDropChance: 0.35,
    color: '#06B6D4',
    badge: 'ACTIVE WORLD EVENT'
  },
  {
    id: 'event-bull-rush',
    title: '🚀 Green Bull Momentum',
    category: 'MARKET_RALLY',
    description: 'High liquidity inflows! All winning trades grant double companion XP and extra Gem bounties.',
    sectors: 'ALL',
    xpMultiplier: 1.5,
    profitMultiplier: 1.15,
    gemDropChance: 0.50,
    color: '#10B981',
    badge: 'MARKET FRENZY'
  },
  {
    id: 'event-whale-wave',
    title: '🐋 Whale Liquidity Influx',
    category: 'HIGH_VOLUME',
    description: 'Mega institutional orders detected! Free +$50 trade execution bonus and zero market slippage.',
    sectors: 'ALL',
    xpMultiplier: 1.3,
    profitMultiplier: 1.20,
    gemDropChance: 0.40,
    color: '#A855F7',
    badge: 'DEEP MATRIX'
  },
];

export const AGENTS_CATALOG = [
  {
    id: 'agent-scout',
    name: 'SCOUT',
    title: 'Rookie Market Companion',
    specialty: 'Dip & Momentum Radar',
    rarity: 'COMMON',
    unlockCostGems: 0,
    isStarter: true,
    orbColor: 'violet',
    avatarGlow: '#8B5CF6',
    level: 1,
    xp: 0,
    xpMax: 100,
    skillName: 'Dip & Momentum Radar',
    skillDescription: 'Scans live tickers 24/7 to identify oversold dip opportunities and high-probability momentum breakouts.',
    perks: [
      'Beginner signal radar (+10% guidance accuracy)',
      'Earns +25 Bonus XP on every completed trade',
      'Basic dynamic stop-loss indicators'
    ],
    skillTree: [
      { levelReq: 1, name: 'Dip Scanner v1', desc: 'Alerts you to oversold pullbacks' },
      { levelReq: 3, name: 'Momentum Lock', desc: '+5% higher profit on swing trades' },
      { levelReq: 5, name: 'XP Booster Module', desc: '+25% bonus XP when trading with SCOUT' },
      { levelReq: 10, name: 'Master Scout Radar', desc: 'Predicts dip recovery 15s in advance' }
    ],
    stats: { accuracy: 72, speed: 68, profitBonus: 5, shield: 25 },
    trainCostGems: 15,
    bio: 'Your loyal starter AI companion. SCOUT calibrates your entry timing and guides you to earn your first competitive league badges.'
  },
  {
    id: 'agent-oracle',
    name: 'ORACLE',
    title: 'The Breakout Seer',
    specialty: 'Neural Trend Predictor',
    rarity: 'RARE',
    unlockCostGems: 50,
    isStarter: false,
    orbColor: 'emerald',
    avatarGlow: '#10B981',
    level: 1,
    xp: 0,
    xpMax: 150,
    skillName: 'Neural Surge Forecast',
    skillDescription: 'Forecasts price direction before breakout candles occur with 88% predictive algorithmic precision.',
    perks: [
      '88% Win-rate directional buy/sell signals',
      'Highlights optimal dip-buying reversal points',
      '+12% profit bonus multiplier on profitable trades'
    ],
    skillTree: [
      { levelReq: 1, name: 'Neural Seer', desc: '88% accuracy on trend breakouts' },
      { levelReq: 3, name: 'Harmonic Oscillator', desc: '+15% profit on green candles' },
      { levelReq: 5, name: 'Crystal Vision', desc: 'Unlocks advanced predictive chart overlays' },
      { levelReq: 10, name: 'Omniscient Trader', desc: 'Guarantees +20% minimum payout boost' }
    ],
    stats: { accuracy: 88, speed: 78, profitBonus: 12, shield: 45 },
    trainCostGems: 25,
    bio: 'Powered by predictive neural regression networks. ORACLE decodes market micro-structures before price movements manifest.'
  },
  {
    id: 'agent-quantum',
    name: 'QUANTUM',
    title: 'High-Frequency Scalper',
    specialty: 'Instant Micro-Scalping & Yield',
    rarity: 'EPIC',
    unlockCostGems: 100,
    isStarter: false,
    orbColor: 'cyan',
    avatarGlow: '#06B6D4',
    level: 1,
    xp: 0,
    xpMax: 220,
    skillName: 'Passive Yield & Sub-Second Scalp',
    skillDescription: 'Harvests micro-spreads 24/7, generating +$25 passive cash dividend every 30s during active sessions.',
    perks: [
      'Passive cash dividend yield ($25 every 30 seconds)',
      'Sub-millisecond simulated execution speed',
      '+18% profit multiplier on rapid day trades'
    ],
    skillTree: [
      { levelReq: 1, name: 'Micro-Scalp Core', desc: '+$25 passive yield every 30 seconds' },
      { levelReq: 3, name: 'Spread Arbitrage', desc: '+15% day-trading profit bonus' },
      { levelReq: 5, name: 'Overclocked Matrix', desc: 'Increases passive yield to +$50/30s' },
      { levelReq: 10, name: 'Zero-Latency Singularity', desc: 'Doubles all scalping trade XP' }
    ],
    stats: { accuracy: 84, speed: 99, profitBonus: 18, shield: 50 },
    trainCostGems: 35,
    bio: 'An ultra-low latency algorithmic engine that harvests fractional spreads across the market ticker in milliseconds.'
  },
  {
    id: 'agent-valkyrie',
    name: 'VALKYRIE',
    title: 'Tech & Growth Hunter',
    specialty: 'High-Beta Rallies & Multipliers',
    rarity: 'EPIC',
    unlockCostGems: 175,
    isStarter: false,
    orbColor: 'pink',
    avatarGlow: '#EC4899',
    level: 1,
    xp: 0,
    xpMax: 300,
    skillName: 'Exponential Tech Multiplier',
    skillDescription: 'Detects high-volatility semiconductor and AI stock rallies with an active +25% profit multiplier.',
    perks: [
      '+25% Profit multiplier on Technology & AI stocks',
      'Highlights 10x breakout momentum stocks',
      'Unlocks high-roller position sizing in Arena'
    ],
    skillTree: [
      { levelReq: 1, name: 'Tech Radar', desc: '+25% profit on NVDA, AMD, MSFT, PLTR' },
      { levelReq: 3, name: 'High-Beta Overdrive', desc: 'Extra +50 XP per tech stock win' },
      { levelReq: 5, name: 'Exponential Surge', desc: '+30% profit multiplier boost' },
      { levelReq: 10, name: 'Valkyrie Ascendance', desc: 'Unlocks 1.5x trade volume leverage' }
    ],
    stats: { accuracy: 91, speed: 88, profitBonus: 28, shield: 40 },
    trainCostGems: 45,
    bio: 'Relentless growth hunter specialized in high-beta tech equities, semiconductor surges, and exponential rallies.'
  },
  {
    id: 'agent-aegis',
    name: 'AEGIS',
    title: 'Crash Shield & Hedge Master',
    specialty: 'Loss Capping & Risk Shielding',
    rarity: 'LEGENDARY',
    unlockCostGems: 250,
    isStarter: false,
    orbColor: 'gold',
    avatarGlow: '#F59E0B',
    level: 1,
    xp: 0,
    xpMax: 400,
    skillName: 'Max -2% Drawdown Shield',
    skillDescription: 'Auto-hedges your portfolio against sudden market dumps, capping any single trade loss at just -2%.',
    perks: [
      'Maximum loss cap at only -2% per position',
      'Early warning flash before market dips',
      'Emergency 1-click portfolio hedge & recovery'
    ],
    skillTree: [
      { levelReq: 1, name: 'Aegis Armor v1', desc: 'Caps position losses at -2%' },
      { levelReq: 3, name: 'Flash Warning Sensor', desc: 'Highlights downward spikes in real-time' },
      { levelReq: 5, name: 'Ironclad Bastion', desc: 'Free stop-loss execution without fee' },
      { levelReq: 10, name: 'Invulnerable Citadel', desc: 'Converts 25% of all losses into Bonus XP' }
    ],
    stats: { accuracy: 94, speed: 92, profitBonus: 15, shield: 99 },
    trainCostGems: 60,
    bio: 'The impenetrable risk optimizer. AEGIS guarantees you preserve capital even through unexpected market flash crashes.'
  },
  {
    id: 'agent-titan',
    name: 'TITAN',
    title: 'The Apex Market Whale',
    specialty: 'Liquidity Dominance & Gem Yields',
    rarity: 'MYTHIC',
    unlockCostGems: 400,
    isStarter: false,
    orbColor: 'purple',
    avatarGlow: '#A855F7',
    level: 1,
    xp: 0,
    xpMax: 600,
    skillName: '3x Margin Leverage & Daily Gems',
    skillDescription: 'Unlocks 3x Margin buying power in the Arena and passively drops +5 💎 Nexus Gems every 24 hours.',
    perks: [
      '3x Margin virtual buying power',
      '+5 💎 Premium Nexus Gems daily passive bonus',
      '+35% Profit multiplier on all successful trades'
    ],
    skillTree: [
      { levelReq: 1, name: 'Whale Liquidity', desc: '3x Buying power & +35% profit boost' },
      { levelReq: 3, name: 'Gem Synthesizer', desc: 'Drops +5 Gems every single day' },
      { levelReq: 5, name: 'Market Domination', desc: '+50% XP on all executed orders' },
      { levelReq: 10, name: 'Galactic Sovereign', desc: 'Unlocks +50% Profit multiplier permanently' }
    ],
    stats: { accuracy: 99, speed: 96, profitBonus: 38, shield: 92 },
    trainCostGems: 80,
    bio: 'The apex market conqueror. TITAN commands colossal liquidity streams, multiplying trading power and gem generation.'
  },
];

export const INITIAL_STOCKS = [
  {
    symbol: 'NVDA',
    name: 'NVIDIA Corporation',
    sector: 'AI & Semiconductors',
    price: 128.50,
    basePrice: 128.50,
    changePercent: 3.85,
    sparkline: [118, 120, 119, 122, 125, 124, 128.5],
    volatility: 'HIGH',
    tier: 'Tier S',
    logoColor: '#76B900',
    news: 'Next-Gen Cyber AI GPU cluster synthesis surges demand.',
  },
  {
    symbol: 'AAPL',
    name: 'Apple Inc.',
    sector: 'Consumer Tech',
    price: 224.20,
    basePrice: 224.20,
    changePercent: 1.45,
    sparkline: [218, 220, 221, 219, 223, 222, 224.2],
    volatility: 'LOW',
    tier: 'Tier A',
    logoColor: '#A2AAAD',
    news: 'New holographic spatial computing device breaks pre-order records.',
  },
  {
    symbol: 'TSLA',
    name: 'Tesla, Inc.',
    sector: 'Clean Energy & Robotics',
    price: 254.10,
    basePrice: 254.10,
    changePercent: 4.60,
    sparkline: [238, 242, 240, 248, 250, 249, 254.1],
    volatility: 'VERY HIGH',
    tier: 'Tier S',
    logoColor: '#E82127',
    news: 'Autonomous robotaxi fleet receives state certification.',
  },
  {
    symbol: 'MSFT',
    name: 'Microsoft Corp.',
    sector: 'Cloud & AI Kernel',
    price: 448.90,
    basePrice: 448.90,
    changePercent: 2.10,
    sparkline: [435, 439, 442, 440, 445, 444, 448.9],
    volatility: 'MEDIUM',
    tier: 'Tier A',
    logoColor: '#00A4EF',
    news: 'Enterprise autonomous agent suite reaches 100M active instances.',
  },
  {
    symbol: 'PLTR',
    name: 'Palantir Technologies',
    sector: 'Defense AI & Data',
    price: 36.40,
    basePrice: 36.40,
    changePercent: 5.80,
    sparkline: [32, 33, 34, 33.5, 35, 34.8, 36.4],
    volatility: 'HIGH',
    tier: 'Tier S',
    logoColor: '#FFFFFF',
    news: 'Secures sovereign cloud intelligence contract for automated defense.',
  },
  {
    symbol: 'COIN',
    name: 'Coinbase Global',
    sector: 'Digital Assets Platform',
    price: 215.80,
    basePrice: 215.80,
    changePercent: -1.25,
    sparkline: [225, 222, 220, 218, 219, 217, 215.8],
    volatility: 'VERY HIGH',
    tier: 'Tier A',
    logoColor: '#0052FF',
    news: 'Consolidation phase detected as institutional trading volume spikes.',
  },
  {
    symbol: 'AMZN',
    name: 'Amazon.com Inc.',
    sector: 'E-Commerce & AWS',
    price: 186.40,
    basePrice: 186.40,
    changePercent: -0.85,
    sparkline: [190, 189, 187, 188, 186, 187, 186.4],
    volatility: 'MEDIUM',
    tier: 'Tier B',
    logoColor: '#FF9900',
    news: 'AWS releases sub-millisecond AI inference micro-nodes.',
  },
  {
    symbol: 'AMD',
    name: 'Advanced Micro Devices',
    sector: 'AI Hardware & Chips',
    price: 154.20,
    basePrice: 154.20,
    changePercent: 2.75,
    sparkline: [146, 148, 150, 149, 152, 151, 154.2],
    volatility: 'HIGH',
    tier: 'Tier A',
    logoColor: '#ED1C24',
    news: 'Unveils next-gen APU processors outperforming benchmarks.',
  },
];

export const INITIAL_MISSIONS = [
  {
    id: 'm-rookie-1',
    category: 'daily',
    tier: 'Daily Quest',
    title: 'First Market Entry',
    description: 'Execute your first stock trade following your active AI agent’s signal in the Arena.',
    progress: 0,
    target: 1,
    unit: 'trades',
    rewardGems: 15,
    rewardCash: 500,
    rewardXP: 100,
    claimed: false,
    badge: '🎯 First Blood',
  },
  {
    id: 'm-rookie-2',
    category: 'daily',
    tier: 'Daily Quest',
    title: 'Lock In First Profit',
    description: 'Sell a winning stock position with at least +$150 positive return.',
    progress: 0,
    target: 150,
    unit: '$ profit',
    rewardGems: 25,
    rewardCash: 750,
    rewardXP: 150,
    claimed: false,
    badge: '💰 Green Scalper',
  },
  {
    id: 'm-tier-1',
    category: 'daily',
    tier: 'Sector Challenge',
    title: 'Tech Sector Surge',
    description: 'Buy shares in 2 distinct AI or Semiconductor companies (NVDA, MSFT, AMD, PLTR).',
    progress: 0,
    target: 2,
    unit: 'tech stocks',
    rewardGems: 20,
    rewardCash: 600,
    rewardXP: 120,
    claimed: false,
    badge: '⚡ Tech Pioneer',
  },
  {
    id: 'm-tier-2',
    category: 'milestone',
    tier: 'Campaign Milestone',
    title: 'Accumulate $2,000 Profit',
    description: 'Earn a cumulative net trading profit of +$2,000 across all closed positions.',
    progress: 0,
    target: 2000,
    unit: '$ total gain',
    rewardGems: 50,
    rewardCash: 2000,
    rewardXP: 350,
    claimed: false,
    badge: '📈 Profit Engine',
  },
  {
    id: 'm-tier-3',
    category: 'milestone',
    tier: 'Agent Forge Quest',
    title: 'Recruit a 2nd AI Companion',
    description: 'Unlock ORACLE or QUANTUM in the Agent Forge using earned 💎 Nexus Gems.',
    progress: 1,
    target: 2,
    unit: 'agents owned',
    rewardGems: 60,
    rewardCash: 2500,
    rewardXP: 400,
    claimed: false,
    badge: '🤖 AI Syndicate',
  },
  {
    id: 'm-tier-4',
    category: 'milestone',
    tier: 'High-Roller Goal',
    title: 'Reach $25,000 Net Worth',
    description: 'Grow your virtual cash and open stock positions to $25,000+ to unlock Silver League.',
    progress: 10000,
    target: 25000,
    unit: '$ net worth',
    rewardGems: 80,
    rewardCash: 3500,
    rewardXP: 600,
    claimed: false,
    badge: '💎 Silver Voyager',
  },
];

export const ACHIEVEMENTS_LIST = [
  {
    id: 'ach-first-trade',
    title: 'First Blood',
    description: 'Execute your very first trade in the Trading Arena.',
    icon: '🎯',
    target: 1,
    type: 'trades',
    rewardGems: 10,
    rewardXP: 50,
    unlocked: false,
  },
  {
    id: 'ach-profit-1k',
    title: 'Centurion Scalper',
    description: 'Generate over $1,000 in realized trading profits.',
    icon: '💵',
    target: 1000,
    type: 'profit',
    rewardGems: 25,
    rewardXP: 150,
    unlocked: false,
  },
  {
    id: 'ach-streak-3',
    title: 'Dedicated Commander',
    description: 'Maintain a 3-day daily login streak.',
    icon: '🔥',
    target: 3,
    type: 'streak',
    rewardGems: 20,
    rewardXP: 120,
    unlocked: false,
  },
  {
    id: 'ach-agents-3',
    title: 'Companion Fleet',
    description: 'Unlock 3 distinct AI companion agents in the Forge.',
    icon: '🤖',
    target: 3,
    type: 'agents',
    rewardGems: 45,
    rewardXP: 300,
    unlocked: false,
  },
  {
    id: 'ach-level-5',
    title: 'Ascendant Scalper',
    description: 'Reach Player Level 5.',
    icon: '⭐',
    target: 5,
    type: 'level',
    rewardGems: 35,
    rewardXP: 250,
    unlocked: false,
  },
  {
    id: 'ach-whale-50k',
    title: 'Market Whale Junior',
    description: 'Achieve a Total Portfolio Net Worth of $50,000+.',
    icon: '🐋',
    target: 50000,
    type: 'networth',
    rewardGems: 100,
    rewardXP: 800,
    unlocked: false,
  },
];
