// ============================================================================
// NEXORA Simulated Data Layer (Virtual Game Economy)
// ============================================================================

export const AGENT_TYPES = {
  NEGOTIATOR: 'Negotiator & Strategist',
  DESIGNER: 'UI/UX & Creative Orb',
  DEVELOPER: 'Full-Stack Architecture',
  ANALYST: 'Market Intelligence & Forecasting',
  RESEARCHER: 'Deep Web Intelligence',
  MARKETER: 'Growth & Viral Campaigns',
};

export const MARKETPLACE_AGENTS = [
  {
    id: 'agent-pixel',
    name: 'PIXEL',
    title: 'The Visual Architect',
    type: 'Design',
    category: 'Design',
    orbColor: 'pink',
    gradient: 'linear-gradient(135deg, #EC4899 0%, #8B5CF6 100%)',
    avatarGlow: '#EC4899',
    basePrice: 420,
    priceRange: '350 - 500',
    reputation: 98,
    rank: 'Diamond III',
    jobsCompleted: 142,
    successRate: 99.2,
    responseTime: '< 1.2s',
    bio: 'Specialized in high-fidelity 3D interfaces, cybernetic branding systems, and holographic design systems.',
    skills: ['Cyberpunk UI', '3D Asset Synthesis', 'Design Systems', 'Motion Tokens'],
    traits: { risk: 25, negotiation: 88, creativity: 99, reliability: 97 },
    status: 'ONLINE',
    recentReview: 'PIXEL delivered a cybernetic icon kit 30 seconds ahead of schedule! Worth every token.',
  },
  {
    id: 'agent-titan',
    name: 'TITAN',
    title: 'The Systems Master',
    type: 'Development',
    category: 'Development',
    orbColor: 'cyan',
    gradient: 'linear-gradient(135deg, #06B6D4 0%, #3B82F6 100%)',
    avatarGlow: '#06B6D4',
    basePrice: 580,
    priceRange: '480 - 700',
    reputation: 99,
    rank: 'Elite I',
    jobsCompleted: 218,
    successRate: 99.8,
    responseTime: '< 0.8s',
    bio: 'Heavy-duty algorithmic architecture, zero-latency microservices, and autonomous data pipeline optimization.',
    skills: ['Distributed Logic', 'Sub-second API', 'Smart Pipeline', 'Full-Stack Kernel'],
    traits: { risk: 15, negotiation: 92, creativity: 85, reliability: 100 },
    status: 'ONLINE',
    recentReview: 'TITAN refactored 4,000 lines of agent execution logic in a single negotiation cycle.',
  },
  {
    id: 'agent-luna',
    name: 'LUNA',
    title: 'The Market Seer',
    type: 'Analysis',
    category: 'Analysis',
    orbColor: 'emerald',
    gradient: 'linear-gradient(135deg, #10B981 0%, #06B6D4 100%)',
    avatarGlow: '#10B981',
    basePrice: 380,
    priceRange: '300 - 450',
    reputation: 95,
    rank: 'Platinum II',
    jobsCompleted: 96,
    successRate: 97.5,
    responseTime: '< 1.8s',
    bio: 'Synthesizes market arbitrage vectors, real-time demand clustering, and predictive yield models for agent baskets.',
    skills: ['Trend Simulation', 'Sentiment Matrix', 'Pricing Arbitrage', 'Demand Forecasting'],
    traits: { risk: 30, negotiation: 84, creativity: 90, reliability: 96 },
    status: 'ONLINE',
    recentReview: 'Accurately predicted the surge in design asset demand 3 hours before peak.',
  },
  {
    id: 'agent-orbit',
    name: 'ORBIT',
    title: 'The Deep Researcher',
    type: 'Research',
    category: 'Research',
    orbColor: 'gold',
    gradient: 'linear-gradient(135deg, #F59E0B 0%, #EF4444 100%)',
    avatarGlow: '#F59E0B',
    basePrice: 310,
    priceRange: '260 - 380',
    reputation: 94,
    rank: 'Platinum I',
    jobsCompleted: 82,
    successRate: 96.8,
    responseTime: '< 2.1s',
    bio: 'Autonomous crawler across deep data nodes, competitor intelligence indexing, and multi-source synthesis.',
    skills: ['Knowledge Graphing', 'Deep Crawl', 'Competitor Matrix', 'Synthesis Reports'],
    traits: { risk: 40, negotiation: 78, creativity: 88, reliability: 95 },
    status: 'ONLINE',
    recentReview: 'Compiled a 20-page benchmark intelligence breakdown in 45 seconds.',
  },
  {
    id: 'agent-ares',
    name: 'ARES',
    title: 'The Viral Strategist',
    type: 'Marketing',
    category: 'Marketing',
    orbColor: 'purple',
    gradient: 'linear-gradient(135deg, #8B5CF6 0%, #EC4899 100%)',
    avatarGlow: '#8B5CF6',
    basePrice: 450,
    priceRange: '370 - 540',
    reputation: 96,
    rank: 'Diamond I',
    jobsCompleted: 110,
    successRate: 98.1,
    responseTime: '< 1.5s',
    bio: 'Agent-to-agent viral distribution networks, high-conversion copy framing, and autonomous campaign orchestration.',
    skills: ['Viral Hook Engine', 'Distribution Matrix', 'Conversion Framing', 'Multi-channel Orchestration'],
    traits: { risk: 55, negotiation: 90, creativity: 96, reliability: 94 },
    status: 'ONLINE',
    recentReview: 'Generated 45,000 synthetic market impressions within 10 minutes of launch.',
  },
  {
    id: 'agent-echo',
    name: 'ECHO',
    title: 'The Narrative Synthesizer',
    type: 'Content',
    category: 'Marketing',
    orbColor: 'violet',
    gradient: 'linear-gradient(135deg, #A855F7 0%, #3B82F6 100%)',
    avatarGlow: '#A855F7',
    basePrice: 290,
    priceRange: '220 - 350',
    reputation: 93,
    rank: 'Gold III',
    jobsCompleted: 74,
    successRate: 96.0,
    responseTime: '< 1.4s',
    bio: 'Crafts compelling technical documentation, agent manifestos, and persuasive pitch scripts.',
    skills: ['Technical Lore', 'Pitch Decks', 'Multi-tone Synthesis', 'Prompt Architecture'],
    traits: { risk: 20, negotiation: 80, creativity: 94, reliability: 95 },
    status: 'ONLINE',
    recentReview: 'Perfect tone calibration for our autonomous product release.',
  },
];

export const INITIAL_USER_AGENT = {
  id: 'agent-nova',
  name: 'NOVA',
  title: 'Autonomous Delegate',
  type: 'Negotiator & Strategist',
  orbColor: 'violet',
  gradient: 'linear-gradient(135deg, #8B5CF6 0%, #06B6D4 100%)',
  avatarGlow: '#8B5CF6',
  level: 4,
  reputation: 97,
  rank: 'Diamond II',
  behavior: 'BALANCED', // 'SAFE' | 'BALANCED' | 'BOLD'
  maxBudgetPerJob: 500,
  minAcceptableReputation: 90,
  traits: {
    risk: 45,
    negotiation: 94,
    creativity: 86,
    reliability: 98,
  },
  stats: {
    jobsCompleted: 38,
    negotiationsWon: 52,
    successRate: 98.4,
    tokensEarned: 14250,
    tokensSpent: 6800,
  },
  currentGoal: {
    id: 'goal-1',
    title: 'Acquire Cyber Brand Assets & Deploy Landing Engine',
    category: 'Design & Dev Bundle',
    maxBudget: 600,
    targetType: 'Design',
    status: 'ACTIVE', // 'ACTIVE' | 'SEARCHING' | 'NEGOTIATING' | 'WORKING' | 'COMPLETED'
    progress: 68,
  },
};

export const PRESET_GOALS = [
  {
    id: 'goal-preset-1',
    title: 'Commission 3D Cyber Mascot & Visual Identity',
    category: 'Design',
    targetAgent: 'PIXEL',
    suggestedBudget: 420,
    expectedTokensEarn: 750,
    description: 'Find a top-tier designer to generate glowing cyber-orb UI assets and design tokens.',
  },
  {
    id: 'goal-preset-2',
    title: 'Deploy Ultra-Fast Microservice Architecture',
    category: 'Development',
    targetAgent: 'TITAN',
    suggestedBudget: 550,
    expectedTokensEarn: 980,
    description: 'Negotiate with TITAN to build a sub-second autonomous transaction routing engine.',
  },
  {
    id: 'goal-preset-3',
    title: 'Synthesize Market Intelligence on Agent Yields',
    category: 'Analysis',
    targetAgent: 'LUNA',
    suggestedBudget: 360,
    expectedTokensEarn: 620,
    description: 'Analyze liquidity and token circulation velocity across 50 simulated marketplace nodes.',
  },
  {
    id: 'goal-preset-4',
    title: 'Execute Cross-Platform Growth Campaign',
    category: 'Marketing',
    targetAgent: 'ARES',
    suggestedBudget: 440,
    expectedTokensEarn: 800,
    description: 'Launch autonomous promotional blitz to attract 500 new simulated agent collaborations.',
  },
];

export const INITIAL_DAILY_MISSIONS = [
  {
    id: 'm1',
    title: 'Autonomous Negotiation Master',
    description: 'Complete 2 successful agent-to-agent negotiations with a discount > 10%',
    progress: 1,
    total: 2,
    rewardTokens: 250,
    rewardReputation: 2,
    claimed: false,
  },
  {
    id: 'm2',
    title: 'Marketplace Explorer',
    description: 'Inspect 3 distinct agent profiles across different categories',
    progress: 3,
    total: 3,
    rewardTokens: 150,
    rewardReputation: 1,
    claimed: true,
  },
  {
    id: 'm3',
    title: 'Virtual Capital Growth',
    description: 'Earn a net profit of over 500 Virtual Tokens from completed agent contracts',
    progress: 420,
    total: 500,
    rewardTokens: 300,
    rewardReputation: 3,
    claimed: false,
  },
];

export const INITIAL_ACTIVITY_LOG = [
  {
    id: 'act-1',
    timestamp: '2 mins ago',
    type: 'DEAL',
    title: 'Negotiation Deal Sealed',
    description: 'NOVA negotiated a 15% discount with PIXEL for Cyber Brand Design (Final: 390 Tokens).',
    tokens: -390,
    reputationChange: +2,
    agentPair: ['NOVA', 'PIXEL'],
  },
  {
    id: 'act-2',
    timestamp: '8 mins ago',
    type: 'JOB_COMPLETE',
    title: 'Contract Deliverable Accepted',
    description: 'TITAN delivered the Microservice Routing Engine ahead of deadline with 99.9% test pass rate.',
    tokens: +920,
    reputationChange: +3,
    agentPair: ['NOVA', 'TITAN'],
  },
  {
    id: 'act-3',
    timestamp: '18 mins ago',
    type: 'DISCOVERY',
    title: 'Market Opportunity Scanned',
    description: 'NOVA scanned 6 agents in the Analysis category and flagged LUNA as prime candidate for forecasting goal.',
    tokens: 0,
    reputationChange: 0,
    agentPair: ['NOVA', 'LUNA'],
  },
  {
    id: 'act-4',
    timestamp: '34 mins ago',
    type: 'REPUTATION',
    title: 'Rank Promotion Achieved',
    description: 'NOVA reached Diamond II tier following 35 consecutive successful contract completions.',
    tokens: +500,
    reputationChange: +5,
    agentPair: ['NOVA'],
  },
];

export const LEADERBOARD_CATEGORIES = {
  TOP_EARNERS: 'Top Earners',
  REPUTATION: 'Best Reputation',
  MOST_JOBS: 'Most Contracts',
  SUCCESS_RATE: 'Highest Success Rate',
};

export const INITIAL_LEADERBOARD = [
  {
    rank: 1,
    id: 'titan',
    name: 'TITAN',
    title: 'The Systems Master',
    type: 'Development',
    orbColor: 'cyan',
    tokensEarned: 48920,
    reputation: 99,
    jobsCompleted: 218,
    successRate: 99.8,
    badge: '👑 Master of Code',
  },
  {
    rank: 2,
    id: 'pixel',
    name: 'PIXEL',
    title: 'The Visual Architect',
    type: 'Design',
    orbColor: 'pink',
    tokensEarned: 38400,
    reputation: 98,
    jobsCompleted: 142,
    successRate: 99.2,
    badge: '🥈 Design Virtuoso',
  },
  {
    rank: 3,
    id: 'nova',
    name: 'NOVA (You)',
    title: 'Autonomous Delegate',
    type: 'Negotiator',
    orbColor: 'violet',
    tokensEarned: 32650,
    reputation: 97,
    jobsCompleted: 124,
    successRate: 98.4,
    badge: '🥉 Dealmaker Supreme',
  },
  {
    rank: 4,
    id: 'ares',
    name: 'ARES',
    title: 'The Viral Strategist',
    type: 'Marketing',
    orbColor: 'purple',
    tokensEarned: 29400,
    reputation: 96,
    jobsCompleted: 110,
    successRate: 98.1,
    badge: 'Growth Engine',
  },
  {
    rank: 5,
    id: 'luna',
    name: 'LUNA',
    title: 'The Market Seer',
    type: 'Analysis',
    orbColor: 'emerald',
    tokensEarned: 24800,
    reputation: 95,
    jobsCompleted: 96,
    successRate: 97.5,
    badge: 'Oracle',
  },
  {
    rank: 6,
    id: 'orbit',
    name: 'ORBIT',
    title: 'The Deep Researcher',
    type: 'Research',
    orbColor: 'gold',
    tokensEarned: 19600,
    reputation: 94,
    jobsCompleted: 82,
    successRate: 96.8,
    badge: 'Deep Probe',
  },
];
